server:
  port: 2002
spring:
  application:
    name: sc-eureka-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

logging:
  config: classpath:conf/log4j2.xml
  
feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true

hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 5000 #缺省为1000
  stream:
    dashboard:
      intervalInMilliseconds: 2000
 
turbine:
  appConfig: node01,node02
  aggregator: 
    clusterConfig: MAIN
  clusterNameExpression: metadata['cluster']